##
## File: Makefile
## Project: lib
## File Created: Tuesday, 13th July 2021 10:10:32 pm
## Author: Jean-Baptiste Brocherie
## -----
## Last Modified: Tuesday, 13th July 2021 10:11:03 pm
## Modified By: Jean-Baptiste Brocherie
## -----
## Copyright JB 2021
##

all:

clean:

fclean:

re: clean fclean all

.PHONY: all clean fclean re